config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

#customersコントローラー用
  get '/customers/mypage' => 'customers#show', as: 'mypage'
  get '/customers/edit/data' => 'customers#edit', as: 'customers_edit' #edit_customer_registration_pathとURLがかぶるため/customers/edit→/customers/edit/dataに変更
  patch 'customers' => 'customers#update', as: 'customers_update'
  get '/customers/check' => 'customers#check', as: 'customers_check'
  patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'

#エンドユーザー権限では、editはdeviseで標準であるものは使用しない。
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

#homesコントローラー
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

 #管理者側コントローラー
 namespace :admin do
   #get '/' => 'homes#top', as: '' 名前付きルートadmin_pathにしたければこれでも
   root to: 'homes#top'
   resources :items, only:[:index, :create, :new, :edit, :show, :update]
   resources :customers, only:[:index, :show, :edit, :update]
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  #refile用のリレーション
  has_many :item_images, dependent: :destroy
  accepts_attachments_for :item_images, attachment: :image
  #accepts_attachments_for :article_images, attachment: :image, append: true
  #オプション
  #update編集アクションの際、ファイルの上書き（消す）または元のファイルを保持して追加（消さない）を切り替える
  #ファイルを上書きする・・・デフォルト設定、オプションを書かない
  #元のファイルを保持し追加アップロードする・・・append: true

end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @image_number = 1
    #写真のスライドショー実行時に使用

    @item = Item.find(params[:id])
  #Itemモデルから登録した商品を探す
    if @item.item_images.present?
      @item_images = @item.item_images
    end
  #登録したItemモデルにアソシエーションしているitem_imagesモデルのデータを全て取得．ただしあれば。なければスルー。
  end

  def index
    @items = Item.all
    #Itemモデルの全データ取得
  end

  def edit
    @item = Item.find(params[:id])
    #製品データ取得
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, item_images_images: [])
  end
#複数画像を保存する際のストロングパラメータへの記述の仕方
#(子のテーブル名)_(image_id + s): []。もちろんrefileなのでidは省略
#配列の各要素に格納されたファイルがひとつずつ、子のテーブルのimage_idカラムに保存されていく
#したがってfindメソッドで1つずつ取り出すこともできる(1レコードに1つのimage_idが保存されていく感じ)

#なお、子のテーブルにはitem_idというカラムがありますが、テーブル同士のリレーション関係があるため、
#ファイル保存の際にレコードが生成されると自動で親のレコードのidが入力さる。したがって改めて値を入れて保存する必要が無い。

end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  #devise利用の機能（ユーザ登録、ログイン認証など）が使われる場合、その前にconfigure_permitted_parametersが実行される。

    def after_sign_in_path_for(resource)#サインインする前にここを実行してください．(resource)でログインする人の情報を取得．
    #p resource #ここの記述で中身を知れるメソッド
      case resource
      when Admin
        admin_root_path#pathは設定したい遷移先へのpathを指定(resourceの中身がAdminならここに遷移)
      when Customer
        root_path#ここもpathはご自由に変更可能(Customerならこっちに遷移)
      end
    #ここでいうAdminとCustomerはモデル

    end

    def after_sign_out_path_for(resource)
    #p resource #ここの記述で中身を知れるメソッド
      case resource
      when :admin
        new_admin_session_path#pathは設定したい遷移先へのpathを指定(resourceの中身がAdminならここに遷移)
      when :customer
        root_path#ここもpathはご自由に変更可能(Customerならこっちに遷移)
      end
    end


  #リソースの中身に入っている値を見て，条件式に記述する内容を決めてあげる


  #deviseのストロングパラメーター設定
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    #サインアップするときに送信するデータで，送信を許可する項目をkeysで指定
    #サインイン時にもemailとパスワード以外にデータを送信する必要があれば記載する
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:])　こんな感じ．同じアクション内に記述
    #初期設定で用意されていないemailとencrypted_password以外のカラムを使用するときは必要な記述。
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
 def top
   
 end
 
 def about
   
 end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/items/edit.html.erb
<!--商品編集画面-->
<div class="container">
  <div class="row">
    <div class="mx-auto">

      <div class="title" >登録情報更新</div>

      <%= form_with model: @item, url: admin_item_path, local:true do |f| %>
        <h6>商品画像(追加する場合以前登録した画像は残りません)</h6>
        <%= f.attachment_field :item_images_images, multiple: true %>
        <!--　:(子のテーブル名)_(image_id + s) =>:article_images_images (2つの"s"が必要です)。ただしrefileを使用するときはidを省略するので記述しない。
        属性を追加：~~~ , multiple: true　-->

        <!--このように設定すると、単一のファイルではなく複数ファイルの配列を受け取るようになります。（ファイルは1つでも可）
        ※その後の処理の流れでは、アップロードされたファイル毎に個別で種々の処理が実行されていきます(*1)。-->

        <h6>商品名</h6>
        <%= f.text_field :name %>

        <h6>商品説明</h6>
        <%= f.text_area :introduction, size: "50x10" %>

        <h6>税抜き価格</h6>
        <%= f.text_field :price %>円

        <br /><%= f.submit '編集完了', class: "mt-3 btn btn-success" %>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="d-flex">
    <% @items.each do |item| %>
      <div class="thumbnail-box">
        <div>
          <% thumbnail_images = item.item_images %>
        <!--1つの商品とアソシエーションを組んだ全写真データを取得-->
          <% thumbnail_image = thumbnail_images[0] %>
        <!--サムネイル用に先頭の写真1枚だけ取得-->
          <%= link_to admin_item_path(item.id) do %>
            <%= attachment_image_tag thumbnail_image, :image, :fill, 300,225, format: 'jpeg' %>
          <% end %>
        <!--ここまでの記述で、取得した写真を載せる-->
        </div>

        <div class="font-weight-bold"><!--太字のclass-->
          <%= item.name %>
        </div>

        <div class="font-weight-bold">
          ￥<%= item.price %>
        </div>
      </div>
    <% end %>
    <!--商品の数だけ繰り返す-->

  </div>
</div>

app/views/admin/items/new.html.erb
<!--商品登録画面-->
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <div class="title" >商品新規登録</div>
      <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
        <h6>商品画像</h6>
        <%= f.attachment_field :item_images_images, multiple: true %>
        <!--　:(子のテーブル名)_(image_id + s) =>:article_images_images (2つの"s"が必要です)。ただしrefileを使用するときはidを省略するので記述しない。
        属性を追加：~~~ , multiple: true　-->

        <!--このように設定すると、単一のファイルではなく複数ファイルの配列を受け取るようになります。（ファイルは1つでも可）
        ※その後の処理の流れでは、アップロードされたファイル毎に個別で種々の処理が実行されていきます(*1)。-->

        <h6>商品名</h6>
        <%= f.text_field :name %>

        <h6>商品説明</h6>
        <%= f.text_area :introduction %>

        <h6>税抜き価格</h6>
        <%= f.text_field :price %>円

        <br><%= f.submit '新規登録', class: "mt-3 btn btn-success" %></br>
      <% end %>
    </div>

  </div>

</div>

app/views/admin/items/show.html.erb
<div class="d-flex flex-row">
  <div class="sidebar mr-auto"></div>

  <div class="d-flex flex-colum">
    <div id="image_box" class="carousel slide" data-ride="carousel" data-interval=3000>
    <!--3000ミリ秒でスライド-->
      <h1 class="product_detail_title">商品詳細</h1>

      <% if @item_images.present? %>

        <ol class="carousel-indicators">
          <% @item_images.each_with_index do |item_image, index| %>
            <% if index == 0 %>
              <li data-target="#image_box" data-slide-to="0" class="active"></li>
            <% else %>
              <li data-target="#image_box" data-slide-to="#{index}"></li>
            <% end %>
          <% end %>
        </ol>
        <!--初回のみactiveのclass付与が必要なため、ifで条件分岐-->

        <div class="carousel-inner">
          <% @item_images.each do |item_image| %>
            <% if @image_number == 1 %>
              <div class="carousel-item active">
                <%= attachment_image_tag item_image, :image, :fill, 300,300, format: 'jpeg' %>
              </div>
               <!--1枚目のみactiveをclassに付与-->
              <% @image_number = @image_number + 1 %>
              <!--if文で2回目以降を条件分岐でelse側の分を実行-->
              <!--インジケーターのようにindexで持たせても出来る。面倒くさいが無理やりこうすることもできる。-->
            <% else %>
              <div class="carousel-item">
                <%= attachment_image_tag item_image, :image, :fill, 300,300, format: 'jpeg' %>
              </div>
            <% end %>
          <% end %>
          <a class="carousel-control-prev" href="#image_box" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#image_box" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <!--refileの複数画像表示は名前で決まる。数字なら1から。漢字や平仮名は要検証-->
      <% else %>
        <div>
          <%= image_tag('no_image.jpg') %>
        </div>
      <% end %>
    </div>
  </div>

    <div class="product_data bg-white">

      <table class="table">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>

        <tr>
          <td>税込み価格(税抜き価格)</td>
          <td><%= @item.price * 1.10 %>(<%= @item.price %>)円</td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= safe_join(@item.introduction.split("\n"),tag(:br)) %></td>
          <!--safe_join(@item.introduction.split("\n"),tag(:br)),これによってform_withの改行入力が実際に反映できる。-->
        </tr>
      </table>

      <div class="edit-button mx-auto">
          <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>

    </div>

  <div class="sidebar ml-auto"></div>
</div>