config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

#customersコントローラー用
  get '/customers/mypage' => 'customers#show', as: 'mypage'
  get '/customers/edit/data' => 'customers#edit', as: 'customers_edit' #edit_customer_registration_pathとURLがかぶるため/customers/edit→/customers/edit/dataに変更
  patch 'customers' => 'customers#update', as: 'customers_update'
  get '/customers/check' => 'customers#check', as: 'customers_check'
  patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'

#エンドユーザー権限では、editはdeviseで標準であるものは使用しない。
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

#homesコントローラー
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

 #管理者側コントローラー
 namespace :admin do
   #get '/' => 'homes#top', as: '' 名前付きルートadmin_pathにしたければこれでも
   root to: 'homes#top'
   resources :items, only:[:index, :create, :new, :edit, :show, :update]
   resources :customers, only:[:index, :show, :edit, :update]
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  #refile用のリレーション
  has_many :item_images, dependent: :destroy
  accepts_attachments_for :item_images, attachment: :image
  #accepts_attachments_for :article_images, attachment: :image, append: true
  #オプション
  #update編集アクションの際、ファイルの上書き（消す）または元のファイルを保持して追加（消さない）を切り替える
  #ファイルを上書きする・・・デフォルト設定、オプションを書かない
  #元のファイルを保持し追加アップロードする・・・append: true

end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @image_number = 1
    #写真のスライドショー実行時に使用

    @item = Item.find(params[:id])
  #Itemモデルから登録した商品を探す
    if @item.item_images.present?
      @item_images = @item.item_images
    end
  #登録したItemモデルにアソシエーションしているitem_imagesモデルのデータを全て取得．ただしあれば。なければスルー。
  end

  def index
    @items = Item.all
    #Itemモデルの全データ取得
  end

  def edit
    @item = Item.find(params[:id])
    #製品データ取得
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, item_images_images: [])
  end
#複数画像を保存する際のストロングパラメータへの記述の仕方
#(子のテーブル名)_(image_id + s): []。もちろんrefileなのでidは省略
#配列の各要素に格納されたファイルがひとつずつ、子のテーブルのimage_idカラムに保存されていく
#したがってfindメソッドで1つずつ取り出すこともできる(1レコードに1つのimage_idが保存されていく感じ)

#なお、子のテーブルにはitem_idというカラムがありますが、テーブル同士のリレーション関係があるため、
#ファイル保存の際にレコードが生成されると自動で親のレコードのidが入力さる。したがって改めて値を入れて保存する必要が無い。

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  #devise利用の機能（ユーザ登録、ログイン認証など）が使われる場合、その前にconfigure_permitted_parametersが実行される。

    def after_sign_in_path_for(resource)#サインインする前にここを実行してください．(resource)でログインする人の情報を取得．
    #p resource #ここの記述で中身を知れるメソッド
      case resource
      when Admin
        admin_root_path#pathは設定したい遷移先へのpathを指定(resourceの中身がAdminならここに遷移)
      when Customer
        root_path#ここもpathはご自由に変更可能(Customerならこっちに遷移)
      end
    #ここでいうAdminとCustomerはモデル

    end

    def after_sign_out_path_for(resource)
    #p resource #ここの記述で中身を知れるメソッド
      case resource
      when :admin
        new_admin_session_path#pathは設定したい遷移先へのpathを指定(resourceの中身がAdminならここに遷移)
      when :customer
        root_path#ここもpathはご自由に変更可能(Customerならこっちに遷移)
      end
    end


  #リソースの中身に入っている値を見て，条件式に記述する内容を決めてあげる


  #deviseのストロングパラメーター設定
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    #サインアップするときに送信するデータで，送信を許可する項目をkeysで指定
    #サインイン時にもemailとパスワード以外にデータを送信する必要があれば記載する
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:])　こんな感じ．同じアクション内に記述
    #初期設定で用意されていないemailとencrypted_password以外のカラムを使用するときは必要な記述。
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
 def top
   
 end
 
 def about
   
 end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/174cba21f6.js" crossorigin="anonymous"></script><!--Fontawesome用-->
  </head>

  <body>
    <header class="border-bottom">
      <nav class="navbar">

        <div class="title navbar-brand">
          <%= link_to "渋川屋", root_path, class:"text-dark" %>
        </div>
        <% if admin_signed_in? %>
          <ul class="nav">
            <li>
              <%= link_to "商品新規登録", new_admin_item_path, class:"nav-btn-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "商品一覧", admin_items_path, class:"nav-btn-center-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "会員一覧", root_path, class:"nav-btn-center-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "注文履歴一覧", admin_root_path, class:"nav-btn-center-right btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-btn-right btn btn-outline-primary text-dark" %>
            </li>
          </ul>
        <% elsif customer_signed_in? %>
          <ul class="nav">
            <li>
              <%= link_to "About", about_path, class:"nav-btn-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "商品一覧", root_path, class:"nav-btn-center-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "注文履歴", root_path, class:"nav-btn-center-right btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-btn-right btn btn-outline-primary text-dark" %>
            </li>
          </ul>
        <% else %>
          <ul class="nav">
            <li>
              <%= link_to "About", about_path, class:"nav-btn-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "商品一覧", root_path, class:"nav-btn-center-left btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "新規登録", new_customer_registration_path, class:"nav-btn-center-right btn btn-outline-primary text-dark" %>
            </li>

            <li>
              <%= link_to "ログイン", new_customer_registration_path, class:"nav-btn-right btn btn-outline-primary text-dark" %>
            </li>
          </ul>
        <% end %>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="border-top">
      <!--取り扱う人の名前でも後で入れとく-->
    </footer>
  </body>
</html>